"""CADENCE: a hierarchical controlled latent dynamical system for cross-animal
transfer of intervention responses.

The generative model, for animal ``i`` and recording session ``s``:

    z_{t+1} = z_t + dt * [ F_shared(z_t, u_t)          # species-invariant dynamics
                         + G_shared(z_t) a_t           # species-invariant causal operator
                         + R_i(z_t) ]                  # animal-specific residual dynamics
    y_t^{(i,s)} ~ Poisson( softplus(C_{i,s} z_t + b_{i,s}) )   # animal-specific observation map
    beh_t       = D_shared(z_t)                        # shared behavioural readout

``u_t`` is the exogenous task input (shared, known), ``a_t`` the intervention.

Identifiability, informally
---------------------------
Fix ``F_shared``. Suppose an invertible ``T`` reparameterises the latent state.
For the unperturbed dynamics to be preserved we need
``T F(z, u) = F(T z, u)`` for all ``z, u`` -- i.e. ``T`` must lie in the symmetry
group of the shared flow. When that group is trivial, matching a new animal's
*unperturbed* activity pins its observation map ``C_i`` in the shared latent
frame, and therefore fixes the predicted intervention response ``G_shared(z) a``
without ever observing an intervention in that animal. Degenerate flows (e.g.
isotropic linear dynamics, or dynamics confined to a rotationally symmetric
subspace) admit non-trivial ``T`` and transfer is then provably ambiguous. The
teacher-RNN experiments test exactly this dichotomy.

Parameter partition
-------------------
``shared_parameters()``  -> F, G, D, intervention encoder  (fitted across animals)
``animal_parameters(k)`` -> C, b, residual, encoder read-in (fitted per animal,
                            and for a held-out animal on *unperturbed data only*)
"""

from __future__ import annotations

from dataclasses import dataclass, field

import torch
import torch.nn.functional as F
from torch import nn


# ---------------------------------------------------------------------------
# configuration
# ---------------------------------------------------------------------------
@dataclass
class CadenceConfig:
    latent_dim: int = 24
    input_dim: int = 0              # dimension of exogenous task input u_t
    interv_raw_dim: int = 1         # dimension of the raw intervention descriptor
    interv_code_dim: int = 6        # dimension of the intervention code a_t
    behavior_dim: int = 0           # 0 disables the behavioural readout

    f_hidden: int = 128             # width of F_shared
    f_layers: int = 2
    g_rank: int = 16                # rank of the state-dependent part of G
    residual_rank: int = 3          # rank of animal-specific residual dynamics
    encoder_hidden: int = 128
    encoder_readin: int = 32        # per-animal read-in width
    interv_hidden: int = 64

    dt: float = 1.0
    state_decay: float = 0.0        # optional leak toward 0 for stability

    # regularisation
    residual_l2: float = 1e-3
    g_l2: float = 1e-5
    obs_l2: float = 1e-4

    obs_likelihood: str = "poisson"  # 'poisson' | 'gaussian'
    behavior_likelihood: str = "gaussian"

    # allow the intervention code to carry a short learned temporal kernel so
    # that onset / offset transients are representable
    interv_kernel: int = 0

    # Observation maps are generated by a *shared* embedding of per-unit features
    # (probe depth, cell class, firing statistics, autocorrelation, coupling to
    # the population) plus a small animal-specific free correction. This is what
    # makes a new animal's latent frame identifiable from unperturbed data.
    unit_feature_dim: int = 0
    unit_embed_hidden: int = 96
    free_obs_scale: float = 0.1      # initial scale of the free correction
    free_obs_l2: float = 3e-2        # penalty on the free correction
    tie_readin_to_obs: bool = True   # encoder read-in shares C_i

    animals: tuple[str, ...] = field(default_factory=tuple)
    obs_dims: dict[str, int] = field(default_factory=dict)


# ---------------------------------------------------------------------------
# shared components
# ---------------------------------------------------------------------------
class SharedDynamics(nn.Module):
    """F_shared(z, u): species-invariant autonomous + input-driven dynamics."""

    def __init__(self, cfg: CadenceConfig):
        super().__init__()
        d_in = cfg.latent_dim + cfg.input_dim
        layers: list[nn.Module] = []
        w = d_in
        for _ in range(cfg.f_layers):
            layers += [nn.Linear(w, cfg.f_hidden), nn.Tanh()]
            w = cfg.f_hidden
        self.mlp = nn.Sequential(*layers)
        self.out = nn.Linear(w, cfg.latent_dim)
        # a linear term makes the map close to an LDS at initialisation, which
        # markedly stabilises long open-loop rollouts
        self.lin = nn.Linear(d_in, cfg.latent_dim, bias=False)
        nn.init.zeros_(self.out.weight)
        nn.init.zeros_(self.out.bias)
        nn.init.normal_(self.lin.weight, std=0.05)
        self.decay = cfg.state_decay

    def forward(self, z: torch.Tensor, u: torch.Tensor | None) -> torch.Tensor:
        h = z if u is None else torch.cat([z, u], dim=-1)
        return self.out(self.mlp(h)) + self.lin(h) - self.decay * z


class SharedInterventionOperator(nn.Module):
    """G_shared(z) a: state-dependent, species-invariant causal operator.

        G(z) a = B a + P[ tanh(Wz z) * (Wa a) ]

    The first term is the state-independent push; the second is a low-rank
    multiplicative gain that lets the same physical intervention act differently
    depending on where the shared latent state currently is.
    """

    def __init__(self, cfg: CadenceConfig):
        super().__init__()
        d, m, r = cfg.latent_dim, cfg.interv_code_dim, cfg.g_rank
        self.B = nn.Linear(m, d, bias=False)
        self.Wz = nn.Linear(d, r)
        self.Wa = nn.Linear(m, r, bias=False)
        self.P = nn.Linear(r, d, bias=False)
        nn.init.normal_(self.B.weight, std=0.1)
        nn.init.normal_(self.P.weight, std=0.02)

    def forward(self, z: torch.Tensor, a: torch.Tensor) -> torch.Tensor:
        return self.B(a) + self.P(torch.tanh(self.Wz(z)) * self.Wa(a))

    def state_independent(self, a: torch.Tensor) -> torch.Tensor:
        return self.B(a)


class InterventionEncoder(nn.Module):
    """Maps a raw, physically interpretable intervention descriptor (e.g. ICMS
    amplitude and electrode depth; laser power and site) to the code a_t.

    Keeping this a smooth function of *physical* parameters is what allows
    generalisation to intervention settings never seen during training.
    """

    def __init__(self, cfg: CadenceConfig):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(cfg.interv_raw_dim, cfg.interv_hidden),
            nn.Tanh(),
            nn.Linear(cfg.interv_hidden, cfg.interv_hidden),
            nn.Tanh(),
            nn.Linear(cfg.interv_hidden, cfg.interv_code_dim),
        )
        self.kernel = None
        if cfg.interv_kernel > 0:
            self.kernel = nn.Conv1d(
                cfg.interv_code_dim,
                cfg.interv_code_dim,
                kernel_size=cfg.interv_kernel,
                padding=cfg.interv_kernel - 1,
                groups=cfg.interv_code_dim,
                bias=False,
            )
            with torch.no_grad():
                self.kernel.weight.zero_()
                self.kernel.weight[:, :, 0] = 1.0
        self.code_dim = cfg.interv_code_dim

    def forward(self, raw: torch.Tensor, on: torch.Tensor) -> torch.Tensor:
        """raw: (B, T, interv_raw_dim); on: (B, T) gate in [0, 1]."""
        a = self.net(raw) * on.unsqueeze(-1)
        if self.kernel is not None:
            T = a.shape[1]
            a = self.kernel(a.transpose(1, 2))[:, :, :T].transpose(1, 2)
        return a


class BehaviorReadout(nn.Module):
    """Shared behavioural decoder: behaviour is measured in the same physical
    units in every animal, so this map is deliberately *not* animal-specific."""

    def __init__(self, cfg: CadenceConfig):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(cfg.latent_dim, 64), nn.Tanh(), nn.Linear(64, cfg.behavior_dim)
        )

    def forward(self, z: torch.Tensor) -> torch.Tensor:
        return self.net(z)


# ---------------------------------------------------------------------------
# animal-specific components
# ---------------------------------------------------------------------------
class SharedUnitEmbedding(nn.Module):
    """Shared map from per-unit features to that unit's latent loading and bias.

    Because the same function is applied in every animal, units in different
    animals with similar depth / cell class / firing statistics receive similar
    loadings, which expresses all animals' observation maps in one latent frame.
    """

    def __init__(self, cfg: CadenceConfig):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(cfg.unit_feature_dim, cfg.unit_embed_hidden),
            nn.Tanh(),
            nn.Linear(cfg.unit_embed_hidden, cfg.unit_embed_hidden),
            nn.Tanh(),
            nn.Linear(cfg.unit_embed_hidden, cfg.latent_dim + 1),
        )
        with torch.no_grad():
            self.net[-1].weight.mul_(0.5)
            self.net[-1].bias.zero_()

    def forward(self, feats: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor]:
        out = self.net(feats)
        return out[:, :-1], out[:, -1]


class AnimalModule(nn.Module):
    """Parameters private to one animal (or recording session): the free part of
    the observation map and the residual dynamics.

    The observation map is ``C = C_shared(features) + C_free``, where the first
    term comes from the shared unit embedding and the second is a small,
    strongly-regularised animal-specific correction.
    """

    def __init__(self, cfg: CadenceConfig, n_obs: int, features: torch.Tensor | None = None):
        super().__init__()
        d = cfg.latent_dim
        self.n_obs = n_obs
        self.use_embed = cfg.unit_feature_dim > 0 and features is not None
        if features is not None:
            self.register_buffer("features", features)
        else:
            self.register_buffer("features", torch.zeros(n_obs, max(cfg.unit_feature_dim, 1)))
        scale = cfg.free_obs_scale if self.use_embed else 1.0
        self.C_free = nn.Parameter(torch.randn(n_obs, d) * scale / d**0.5)
        self.b_free = nn.Parameter(torch.zeros(n_obs))
        # animal-specific residual dynamics, low rank: U tanh(V z) + c
        q = cfg.residual_rank
        self.res_V = nn.Parameter(torch.randn(q, d) * 0.01) if q > 0 else None
        self.res_U = nn.Parameter(torch.zeros(d, q)) if q > 0 else None
        self.res_c = nn.Parameter(torch.zeros(d))
        self.__dict__["_embed"] = None

    def bind(self, embed: SharedUnitEmbedding | None) -> None:
        # bypass nn.Module.__setattr__ so the *shared* embedding is not registered
        # as a submodule of every animal (which would duplicate its parameters
        # across the shared and animal-specific optimisers)
        self.__dict__["_embed"] = embed

    def obs_map(self) -> tuple[torch.Tensor, torch.Tensor]:
        if self.use_embed and self._embed is not None:
            Ce, be = self._embed(self.features)
            return Ce + self.C_free, be + self.b_free
        return self.C_free, self.b_free

    # kept for readability elsewhere
    @property
    def C(self) -> torch.Tensor:
        return self.obs_map()[0]

    def residual(self, z: torch.Tensor) -> torch.Tensor:
        if self.res_V is None:
            return self.res_c.expand_as(z)
        return torch.tanh(z @ self.res_V.t()) @ self.res_U.t() + self.res_c

    def rate(self, z: torch.Tensor) -> torch.Tensor:
        C, b = self.obs_map()
        return F.softplus(z @ C.t() + b)

    def linear_obs(self, z: torch.Tensor) -> torch.Tensor:
        C, b = self.obs_map()
        return z @ C.t() + b

    @torch.no_grad()
    def permute_units(self, perm: torch.Tensor) -> None:
        """Relabel which unit is which (negative control).

        Permuting the features *and* the free correction together permutes the
        rows of the effective observation map, so the model's prediction for each
        unit is assigned to a different unit while all marginal statistics of the
        population are preserved.
        """
        self.C_free.copy_(self.C_free[perm])
        self.b_free.copy_(self.b_free[perm])
        if self.use_embed:
            self.features.copy_(self.features[perm])

    def readin(self, y: torch.Tensor) -> torch.Tensor:
        """Encoder read-in tied to the observation map, so that *all*
        animal-specific structure flows through ``C``."""
        C, _ = self.obs_map()
        return y @ C / (self.n_obs**0.5)


class LatentEncoder(nn.Module):
    """Causal encoder: maps a window of observations that *precedes* the
    alignment time into the latent state at the alignment time.

    Only pre-intervention observations are ever fed in, so nothing about the
    causal response can leak into the initial condition.
    """

    def __init__(self, cfg: CadenceConfig):
        super().__init__()
        in_dim = (cfg.latent_dim if cfg.tie_readin_to_obs else cfg.encoder_readin)
        self.gru = nn.GRU(in_dim + cfg.input_dim, cfg.encoder_hidden, batch_first=True)
        self.head = nn.Linear(cfg.encoder_hidden, cfg.latent_dim)
        nn.init.zeros_(self.head.bias)

    def forward(self, h: torch.Tensor) -> torch.Tensor:
        _, hn = self.gru(h)
        return self.head(hn[-1])


# ---------------------------------------------------------------------------
# full model
# ---------------------------------------------------------------------------
class Cadence(nn.Module):
    def __init__(self, cfg: CadenceConfig, unit_features: dict[str, torch.Tensor] | None = None):
        super().__init__()
        self.cfg = cfg
        self.F = SharedDynamics(cfg)
        self.G = SharedInterventionOperator(cfg)
        self.interv = InterventionEncoder(cfg)
        self.encoder = LatentEncoder(cfg)
        self.behavior = BehaviorReadout(cfg) if cfg.behavior_dim > 0 else None
        self.unit_embed = SharedUnitEmbedding(cfg) if cfg.unit_feature_dim > 0 else None
        uf = unit_features or {}
        self.animals = nn.ModuleDict(
            {k: AnimalModule(cfg, cfg.obs_dims[k], uf.get(k)) for k in cfg.animals}
        )
        self.z0_prior = nn.Parameter(torch.zeros(cfg.latent_dim))
        self._bind()

    def _bind(self) -> None:
        for m in self.animals.values():
            m.bind(self.unit_embed)

    # -- parameter partition -------------------------------------------------
    def shared_parameters(self):
        mods = [self.F, self.G, self.interv, self.encoder.gru, self.encoder.head]
        if self.behavior is not None:
            mods.append(self.behavior)
        if self.unit_embed is not None:
            mods.append(self.unit_embed)
        for m in mods:
            yield from m.parameters()
        yield self.z0_prior

    def animal_parameters(self, key: str):
        yield from self.animals[key].parameters()

    def add_animal(self, key: str, n_obs: int, features: torch.Tensor | None = None) -> None:
        self.cfg.obs_dims[key] = n_obs
        self.cfg.animals = tuple(self.cfg.animals) + (key,)
        dev = next(self.parameters()).device
        self.animals[key] = AnimalModule(self.cfg, n_obs, features).to(dev)
        self._bind()

    def set_shared_grad(self, flag: bool) -> None:
        for p in self.shared_parameters():
            p.requires_grad_(flag)

    # -- dynamics ------------------------------------------------------------
    def step(self, z, u_t, a_t, animal: AnimalModule, use_intervention: bool = True):
        dz = self.F(z, u_t) + animal.residual(z)
        if use_intervention and a_t is not None:
            dz = dz + self.G(z, a_t)
        return z + self.cfg.dt * dz

    def encode(self, key: str, y_pre: torch.Tensor, u_pre: torch.Tensor | None):
        """y_pre: (B, L, N_i) pre-intervention observations."""
        animal = self.animals[key]
        h = animal.readin(self._obs_transform(y_pre))
        if u_pre is not None:
            h = torch.cat([h, u_pre], dim=-1)
        return self.encoder(h) + self.z0_prior

    def _obs_transform(self, y: torch.Tensor) -> torch.Tensor:
        if self.cfg.obs_likelihood == "poisson":
            return torch.log1p(y)
        return y

    def rollout(
        self,
        key: str,
        z0: torch.Tensor,
        u: torch.Tensor | None,
        a: torch.Tensor | None,
        n_steps: int,
        use_intervention: bool = True,
    ):
        """Open-loop rollout. No observations are consumed after ``z0``."""
        animal = self.animals[key]
        zs = []
        z = z0
        for t in range(n_steps):
            u_t = None if u is None else u[:, t]
            a_t = None if a is None else a[:, t]
            z = self.step(z, u_t, a_t, animal, use_intervention)
            zs.append(z)
        Z = torch.stack(zs, dim=1)
        out = {"z": Z}
        if self.cfg.obs_likelihood == "poisson":
            out["rate"] = animal.rate(Z)
        else:
            out["mean"] = animal.linear_obs(Z)
        if self.behavior is not None:
            out["behavior"] = self.behavior(Z)
        return out

    def forward(
        self,
        key: str,
        y_pre: torch.Tensor,
        u_pre: torch.Tensor | None,
        u_post: torch.Tensor | None,
        interv_raw: torch.Tensor | None,
        interv_on: torch.Tensor | None,
        n_steps: int,
        use_intervention: bool = True,
    ):
        z0 = self.encode(key, y_pre, u_pre)
        a = None
        if interv_raw is not None and use_intervention:
            a = self.interv(interv_raw, interv_on)
        return self.rollout(key, z0, u_post, a, n_steps, use_intervention)

    # -- losses --------------------------------------------------------------
    def observation_nll(self, pred: dict, y: torch.Tensor, mask: torch.Tensor | None = None):
        if self.cfg.obs_likelihood == "poisson":
            rate = pred["rate"].clamp_min(1e-6)
            nll = rate - y * torch.log(rate) + torch.lgamma(y + 1.0)
        else:
            nll = 0.5 * (pred["mean"] - y) ** 2
        if mask is not None:
            nll = nll * mask.unsqueeze(-1)
            return nll.sum() / mask.sum().clamp_min(1.0) / y.shape[-1]
        return nll.mean()

    def behavior_nll(self, pred: dict, beh: torch.Tensor, mask: torch.Tensor | None = None):
        if "behavior" not in pred:
            return torch.zeros((), device=beh.device)
        err = 0.5 * (pred["behavior"] - beh) ** 2
        if mask is not None:
            err = err * mask.unsqueeze(-1)
            return err.sum() / mask.sum().clamp_min(1.0) / beh.shape[-1]
        return err.mean()

    def regularisation(self, key: str) -> torch.Tensor:
        cfg = self.cfg
        a = self.animals[key]
        reg = cfg.residual_l2 * a.res_c.pow(2).sum()
        if a.res_V is not None:
            reg = reg + cfg.residual_l2 * (a.res_U.pow(2).sum() + a.res_V.pow(2).sum())
        C, _ = a.obs_map()
        reg = reg + cfg.obs_l2 * C.pow(2).sum()
        if a.use_embed:
            # the free correction is what could break the shared latent frame,
            # so it is penalised separately and much more strongly
            reg = reg + cfg.free_obs_l2 * (a.C_free.pow(2).sum() + a.b_free.pow(2).sum())
        reg = reg + cfg.g_l2 * (
            self.G.B.weight.pow(2).sum() + self.G.P.weight.pow(2).sum()
        )
        return reg
